### ISSUE TITLE
Google Chrome CORS Issues

### ISSUE THREAD

**Issue by Muthu-Divum** [jpmorganchase/quorum-remix#30]
When I try to connect the HTTP server, I am getting the following error from the browser.

> Could not connect to http://xx.xx.xx.xx:22000: Network Error. This could be:  a. geth is not running at this address, b. the port is not accessible, or c. CORS settings on geth do not allow this URL (check the developer console for CORS errors)

From the browser console:

> Mixed Content: The page at 'https://jpmorganchase.github.io/qr/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xx.xx.xx.xx:22000/'. This request has been blocked; the content must be served over HTTPS.

`Google Chrome: Version 78.0.3904.97 (Official Build) (64-bit) `
`Remix: Version v0.9.2`
For Connecting remix: [http://remix.ethereum.org/](url)

**Comment by bmcd87** [comment]
In the current version, even if you load remix over http, it loads the plugin from our https site. Chrome and Firefox don't allow you to make cross-origin http requests on https sites, except to http://localhost in Chrome.

We fixed it so that if you load http remix you’ll get the http quorum plugin, but it won't be live until the next Remix release. Our change has been deployed to the Remix alpha channel though, so if you're ok with a less stable version of remix, you can try the plugin out on http://remix-alpha.ethereum.org 

I'll leave this issue open until it's deployed to prod so others can see.

**Comment by bmcd87** [comment]
The latest version of remix will now load the plugin over http or https, depending on whether you load http or http remix.
